#!/bin/bash
sudo apt-get update 
sudo apt-get remove ffmpeg -y
sudo apt-get remove x265 -y
sudo apt-get install ffmpeg -y
sudo apt-get install x265 -y
a=1
for f in *; do
	if [ ${f: -4} == ".mp4" ]
		then
			a=$((a + 1))
			b=".mp4"
			newname=$a$b
			time ffmpeg -threads 8 -i $f -c:v libx265 -preset faster -quality 1 -c:a aac -b:a 128k -strict -2 "compressed"$f -y
			oldName=$f
			rm $f
			mv "compressed"$f $oldName
	fi
done